sudo: false

cache:
  directories:
    - elm-stuff/build-artifacts
    - example/elm-stuff/build-artifacts
    - example/tests/elm-stuff/build-artifacts
    - sysconfcpus
    - node_modules

language: node_js
node_js:
  - "node"

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install -g elm
  - npm install -g elm-test
  - git clone https://github.com/NoRedInk/elm-ops-tooling
  - elm-ops-tooling/with_retry.rb elm-package install --yes

install:
  - npm install

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 1 npm test

notifications:
  email: false
